//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: greeting.proto

package greet;

@kotlin.jvm.JvmSynthetic
public inline fun helloRequest(block: greet.HelloRequestKt.Dsl.() -> kotlin.Unit): greet.Greeting.HelloRequest =
  greet.HelloRequestKt.Dsl._create(greet.Greeting.HelloRequest.newBuilder()).apply { block() }._build()
public object HelloRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: greet.Greeting.HelloRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: greet.Greeting.HelloRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): greet.Greeting.HelloRequest = _builder.build()

    /**
     * <code>string name = 1;</code>
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <code>string name = 1;</code>
     */
    public fun clearName() {
      _builder.clearName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun greet.Greeting.HelloRequest.copy(block: greet.HelloRequestKt.Dsl.() -> kotlin.Unit): greet.Greeting.HelloRequest =
  greet.HelloRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
