//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: greeting.proto

package greet;

@kotlin.jvm.JvmSynthetic
public inline fun helloReply(block: greet.HelloReplyKt.Dsl.() -> kotlin.Unit): greet.Greeting.HelloReply =
  greet.HelloReplyKt.Dsl._create(greet.Greeting.HelloReply.newBuilder()).apply { block() }._build()
public object HelloReplyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: greet.Greeting.HelloReply.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: greet.Greeting.HelloReply.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): greet.Greeting.HelloReply = _builder.build()

    /**
     * <code>string message = 1;</code>
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * <code>string message = 1;</code>
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun greet.Greeting.HelloReply.copy(block: greet.HelloReplyKt.Dsl.() -> kotlin.Unit): greet.Greeting.HelloReply =
  greet.HelloReplyKt.Dsl._create(this.toBuilder()).apply { block() }._build()
