<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeting.proto

namespace GPBMetadata;

class Greeting
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
›
greeting.protogreet"
HelloRequest
name (	"

HelloReply
message (	2=
Greeter2
SayHello.greet.HelloRequest.greet.HelloReplybproto3'
        , true);

        static::$is_initialized = true;
    }
}

